### DISCUSSION TITLE
New fields for Snippets

### DISCUSSION THREAD

**Discussion by linonetwo** [TiddlyWiki/TiddlyWiki5#6670] [Ideas]
I want to make `/` menu to show a list like the one in Notion:

<img width="492" alt="截屏2022-05-02 10 17 10" src="https://user-images.githubusercontent.com/3746270/166176733-9f67152c-e164-40ad-b452-6331dd602f86.png">

So there need to be some additional fields, I suggest adding `preview` for the content shown in the tooltip on the right, and a description for the small text below the title. And an icon image (or two-character text) to show on the left of the title.

Text files should allow `$1` to ask snippet provider to set the cursor `<center>$1</center>`.

For example:

```yml
title: $:/language/Snippets/ListByTag
tags: $:/tags/TextEditor/Snippet
caption: List of tiddlers by tag
description: Useage of list-links macro with a filter
preview: $:/language/Snippets/ListByTag/preview
icon: $:/core/images/heading-3

<<list-links "[tag[task]sort[title]]">>
```

It is not easy to add multi-line wikitext in a field in tid file, we can use a tiddler title in the `preview` field. Snippet menu providers may check tid existence using `$tw.wiki.getTiddlerText` before render preview directly.

```
title: $:/language/Snippets/ListByTag/preview

!! Example here

<<list-links "[tag[task]sort[title]]">>

Looks good?
```

And for i18n... I think we have to provide snippet package for different languages? I don't know a good way to do i18n in plugins and tiddler fields.
