### DISCUSSION TITLE
Use CSS to Prevent Long URLs from Breaking Out Tiddler

### DISCUSSION THREAD

**Discussion by kookma** [TiddlyWiki/TiddlyWiki5#6999] [Ideas]
Copy and paste URLs from Browser address bar when taking notes with TW is quite common.
While you can use pretty link using `[[short-title|long-url]]` but most of time you just paste the url directly in tiddler text.
This makes breaking out the tiddler and overflows out of tiddler boundary.

I use the Cheis Coyier tip [prevent-long-urls-from-breaking-out-of-container](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/)

Is it worth to add this to vanilla theme as below?

```css
.tc-tiddler-frame a
 {

  /* These are technically the same, but use both */
  overflow-wrap: break-word;
  word-wrap:     break-word;
  word-break:    break-word;
  
  /* Adds a hyphen where the word breaks, if supported (No Blink) */
  hyphens: auto;

}
```
