### DISCUSSION TITLE
TW5.com Document Style and Class Prefix

### DISCUSSION THREAD

**Discussion by kookma** [TiddlyWiki/TiddlyWiki5#8268] [General]
In https://tiddlywiki.com/#%24%3A%2F_tw5.com-styles

last part we have

```css
}/* WikiText rules */.multi-columns,
.fourcolumns {
	display: block;
	column-count: 4;
	column-gap: 1em;
	-moz-column-count: 4;
	-moz-column-gap: 1em;
	-webkit-column-count: 4;
	-webkit-column-gap: 1em;
}@media (max-width: 960px) {
	.multi-columns {
		column-count: 2;
	}
}
```

but the convention is to prefix these with `tc-`.

@pmario 
I think these styles are maintained by you! Please take a look.
