### ISSUE TITLE
[Proposal] Change the Issue template to replace "value" elements with "placeholder"

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWiki5#6816]
## Proposal

We should change all `value: |` yaml elements to `placeholder: |` .. So if users don't add or change the text, we do get a _no respons_ info in the issue. 

## Reasoning

At the moment the issue yaml file contains the Configuration element like this: 

```
  - type: textarea
    id: Configuration
    attributes:
      label: TiddlyWiki Configuration
      description: please complete the following information
      value: |
        - Version [e.g. v5.1.24]
        - Saving mechanism [e.g. Node.js, TiddlyDesktop, TiddlyHost etc]
        - Plugins installed [e.g. Freelinks, TiddlyMap]

        ### Desktop (please complete the following information):

        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]

        ### Smartphone (please complete the following information):

        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
    validations:
      required: true
```

Which produce a **placeholder** like this: 

![image](https://user-images.githubusercontent.com/374655/180397366-f12bdd1a-80a8-45e6-8183-77c13e0d3396.png)

If the user doesn't change the text and creates the issue .. The following issue "garbage" will be created. 
The input field has a "required" field set to true. ... BUT still we get issues that contain content, that is hard to work with, since we actually don't know, did the user change something, or is it still the boilerplate text. 

![image](https://user-images.githubusercontent.com/374655/180397510-5228f62c-b4fe-46df-a2e6-a892952fda6c.png)
